- hosts: server
  roles:
<<<<<<< Updated upstream:nginxplaybook.yml
    - firewall  
    - nginx
    - php
    - mysql
    - wordpress
=======
    - { role: geerlingguy.nginx }
>>>>>>> Stashed changes:wordpressplaybook.yml
